language: python

python:
  - "3.6"

virtualenv:
system_site_packages: true

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coveralls

script:
  #- coverage run --source='.' manage.py test
  - pipenv run coverage erase
  - pipenv run pytest --cov --cov-report= --junitxml=junit.xml
  - pipenv run coverage xml -o coverage.xml
  
after_success:
  - pipenv run coveralls