language: python

python:
  - "3.6.5"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver/
  - export PATH=$PATH:$PWD/geckodriver

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

addons:
  postgresql: "9.6"
  firefox: latest

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coveralls

script:
  - pipenv run coverage erase
  - pipenv run pytest --cov --cov-report= --junitxml=junit.xml
  - pipenv run coverage xml -o coverage.xml
  
after_success:
  - pipenv run coveralls