language: python

python:
  - "3.6"

virtualenv:
system_site_packages: true

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - pip install coveralls
  - pip install pipenv
  - pipenv install --dev

script:
  - coverage run --source='.' manage.py test
  
after_success:
- coveralls