# Generated by Django 2.0.4 on 2018-04-30 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180430_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 30, 16, 49, 51, 110120)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 30, 16, 49, 51, 112658)),
        ),
    ]
