# Generated by Django 2.0.5 on 2018-05-04 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180430_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 5, 4, 9, 35, 43, 835242)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 5, 4, 9, 35, 43, 837698)),
        ),
    ]
